export const relevanceVideo = [
    {
        "_id": "63bf6487f6077fd071d461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/w3PchAjnjJo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDGvM8QtrQjt1GVvRNawR-Awmzq-A",
        "title": [
            "9",
            "easy",
            "step",
            "to",
            "be",
            "the",
            "best"
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "Masud Rana",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/x58Ff1-joeU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAncxOL8aggSPJ0Hn1J3PP5YVl8lg",
        "title": [
            "Earn",
            "More",
            "Money",
            "By",
            "Youtube"
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "Shawon",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/DMV1QSzBdcE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBzaXmJZoy3XGiYEjmCHo2wjY8QxA",
        "title": [
            "JOXION",
            "x",
            "THORNE",
            "x",
            "iFeature",
            "-",
            "Unstoppable",
            "[Arcade",
            "Release]",
            "by",
            "NCS",
            "Arcade",
            "5",
            "days",
            "ago",
            "2",
            "minutes,",
            "50",
            "seconds",
            "36,677",
            "views",
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "Foowork",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/KqOSPcQFkyQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDPpfDyqW44S11JXpD6pWmdDwEY5w",
        "title": [
            "ChatGPT",
            "Future",
            "of",
            "AI",
            "|",
            "Eagle",
            "Eyes",
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "rana",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/8I3NTE4cn5s/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDobmOkf5Plpv-2sThX0SlbWETZJg",
        "title": [
            "How",
            "to",
            "use",
            "AI",
            "Art",
            "and",
            "ChatGPT",
            "to",
            "Create",
            "a",
            "Insane",
            "Web",
            "Designs",
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "rana",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/w_sxuDMt_V0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAjRPpev-s0HfUAuuP5J1suN-6dwA",
        "title": [
            "How",
            "to",
            "make:",
            "AI",
            "Animations",
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "rana",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/iUVNspaiBAo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC4d2qu1OpbgVShwvS9Jr6bRI5vRg",
        "title": [
           
           " Music",
           "to",
           "put",
           "you",
           "in",
           "a",
           "better",
           "mood",
           "~",
           "Study",
           "music",
           "-",
           "lofi",
           "/",
           "relax",
           "/",
           "stress",
           "relief",
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "Creative",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/XZ1Ikh_os1U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDNMNFKzon1bRx3a-zZXnvhWAxXYg",
        "title": [
            "Look",
            "|",
            "Mission",
            "Impossible",
            "-",
            "Dead",
            "Reckoning",
            "Part",
            "One",
            "|",
            "Discover",
            "it",
            "in",
            "Dolby",
            "Cinema",
            "by",
            "Dolby",
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "Cinema Wala",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
    {
        "_id": "63bf6487f6dfsdfawe461c6",
        "videoId": "",
        "thumbnailId": "https://i.ytimg.com/vi/7tNtU5XFwrU/hq720_live.jpg?sqp=CMDs_50G-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCv56SeEon2OUgUjQzOEHuvRnRPKA",
        "title": [
           
           " NCS",
           "24/7",
           "-",
           "Copyright",
           "Free",
           "Music",
           "Livestream",
           "🎵",
           "@NoCopyrightSounds",
           "EDM,",
           "Gaming,",
           "Trap,",
           "House,",
           "Dubstep",
           "by",
           "NCS",
           "Arcade"
        ],
        "category": "mycategory",
        "uploader": {
            "_id": "63bf6452f6077fd071d461c3",
            "name": "Tech Zoo",
            "username": "rana",
            "email": "rana028511@gmail.com",
            "passwordHash": "$2a$10$nylEYL1kOKwiUVFM8zy5JOivwW8tIul7Wc01LvRtEV2tOIhz/dUwW",
            "isVerified": false,
            "searches": [],
            "subscribers": [],
            "subscribed": [],
            "watchLater": [],
            "__v": 0
        },
        "like": [],
        "unlike": [],
        "tags": [
            "song",
            "music",
            "video"
        ],
        "createdAt": "2023-01-12T01:38:15.529Z",
        "updatedAt": "2023-01-12T01:38:15.529Z",
        "__v": 0
    },
]